try:
    a = int(input("Heyy, Enter your no: "))
    print(a)

except Exception as e:
    print(e)


else:
    print("I'm inside the else ")#It'ill run if try was sucess full